FROM registry.fedoraproject.org/fedora-minimal:35

LABEL name="dirsrv" \
      vendor="389 Directory Server" \
      version="2.0.12" \
      release="20211217" \
      url="https://www.port389.org" \
      summary="389 Directory Server" \
      description="389 Directory Server is an LDAPv3 compliant server" \
      maintainer="389 Directory Server <389-devel@lists.fedoraproject.org>" \
      com.redhat.component="389-ds-base" \
      io.k8s.description="389 Directory Server Container" \
      io.k8s.display-name="389 Directory Server Container" \
      io.openshift.expose-services="3389:3636" \
      io.openshift.tags="ldap,directory server,identity management"

RUN microdnf update -y && microdnf install -y --setopt=install_weak_deps=0 389-ds-base && microdnf clean all

# Workaround for https://github.com/389ds/389-ds-base/issues/5124
RUN sed -i -e 's@^pid_file.*@pid_file = /run/dirsrv/slapd-{instance_name}.pid@g' /usr/share/dirsrv/inf/defaults.inf

RUN mkdir -p /data/config && \
    mkdir -p /data/ssca && \
    mkdir -p /data/run && \
    ln -sf /data/config /etc/dirsrv/slapd-localhost && \
    ln -sf /data/ssca /etc/dirsrv/ssca && \
    ln -sf /data/run /run/dirsrv && \
    chown -R dirsrv: /data && \
    chown -R dirsrv: /run/dirsrv && \
    chgrp -R dirsrv /etc/dirsrv 

EXPOSE 3389 3636

USER dirsrv
CMD [ "/usr/libexec/dirsrv/dscontainer", "-r" ] 
