FROM registry.fedoraproject.org/fedora-minimal:37

LABEL name="dirsrv" \
      vendor="389 Directory Server" \
      url="https://www.port389.org" \
      summary="389 Directory Server" \
      description="389 Directory Server is an LDAPv3 compliant server" \
      maintainer="389 Directory Server <389-devel@lists.fedoraproject.org>" \
      com.redhat.component="389-ds-base" \
      io.k8s.description="389 Directory Server Container" \
      io.k8s.display-name="389 Directory Server Container" \
      io.openshift.expose-services="3389:3636" \
      io.openshift.tags="ldap,directory server,identity management"

RUN microdnf update -y && microdnf install -y --setopt=install_weak_deps=0 389-ds-base tar && microdnf clean all

RUN mkdir -p /data/config && \
    mkdir -p /data/ssca && \
    mkdir -p /data/run && \
    ln -sf /data/config /etc/dirsrv/slapd-localhost && \
    ln -sf /data/ssca /etc/dirsrv/ssca && \
    ln -sf /data/run /run/dirsrv && \
    chown -R dirsrv: /data && \
    chown -R dirsrv: /run/dirsrv && \
    chgrp -R dirsrv /etc/dirsrv

EXPOSE 3389 3636

#USER dirsrv
CMD [ "/usr/libexec/dirsrv/dscontainer", "-r" ]
