.PHONY: help

help: ## Show this help
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

.DEFAULT_GOAL := help

# Container tasks
build: ## Build the container
	../bin/build.sh

build-nc: ## Build the container without caching
	../bin/build-nc.sh

clean: ## Remove all running containers
	../bin/cleanup.sh
