apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: scc-dirsrv
readOnlyRootFilesystem: false
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAs
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
- svc-dirsrv
volumes:
- configMap
- emptyDir
- persistentVolumeClaim
- secret
defaultAddCapabilities: []
priority: 0
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowHostDirVolumePlugin: false