name: Keepalive
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  keepalive:
    name: keepalive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/keepalive-workflow@master
        with:
          commit_message: keepalive
          committer_username: vashirov
          committer_email: vashirov@redhat.com

